from typing import List, Optional
from pydantic import BaseModel, Field


class GeneratedTags(BaseModel):
    primary_tags: List[str] = Field(default_factory=list, description="Primary tags generated by LLM")
    concerns: List[str] = Field(default_factory=list, description="Target client concerns mapped to this entity")
    benefits: List[str] = Field(default_factory=list, description="Core benefits of the entity")
    synonyms: List[str] = Field(default_factory=list, description="Common synonyms or alternative spellings")
    modality: Optional[str] = Field(None, description="Calculated modality for the treatment or device")
    family: Optional[str] = Field(None, description="General functional group family")
    excludes: List[str] = Field(default_factory=list, description="Exclusion keywords or negative constraints")


class SingleTagRequest(BaseModel):
    dry_run: bool = Field(default=False, description="Generate tags but do not commit changes to the database")
    force: bool = Field(default=False, description="Regenerate tags even if the entity has already been processed")


class SingleTagResponse(BaseModel):
    entity_id: str = Field(..., description="UUID of the tagged treatment or device")
    entity_type: str = Field(..., description="Type of the entity ('treatment' or 'device')")
    entity_name: str = Field(..., description="Name of the entity")
    status: Optional[str] = Field(None, description="Tag status (e.g. 'skipped_already_tagged')")
    tags: Optional[GeneratedTags] = Field(None, description="LLM generated tags data")


class BatchTagRequest(BaseModel):
    dry_run: bool = Field(default=False, description="Generate tags but do not save them to the database")
    entity_type: str = Field(default="all", description="Entity categories to run: 'treatment' | 'device' | 'all'")
    limit: Optional[int] = Field(default=None, description="Max rows to process per entity table")
    force: bool = Field(default=False, description="Re-run tag generation even for already tagged rows")
    background: bool = Field(default=True, description="Run as a background task. If False, runs synchronously (may timeout)")


class BatchTagResponse(BaseModel):
    message: str = Field(..., description="Status message detailing job execution state")
    task_id: Optional[str] = Field(None, description="Unique background task ID, if run in the background")
    total_success: Optional[int] = Field(None, description="Count of successfully processed entities (synchronous only)")
    total_skipped: Optional[int] = Field(None, description="Count of skipped entities (synchronous only)")
    total_failed: Optional[int] = Field(None, description="Count of failed entities (synchronous only)")
